# Generated by Django 4.2.6 on 2023-11-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_bid_category_bidhistory_listing_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bidhistory",
            options={
                "verbose_name": "Bid History",
                "verbose_name_plural": "Bid Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="bid",
            name="ammount",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
