# Generated by Django 4.2.6 on 2023-11-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_listing_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="url",
            field=models.URLField(default="https://fakeimg.pl/350x350/?text=image"),
        ),
    ]
